### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by raurr** [IDAES/idaes-ext#271]
I am trying to run watertap3 and I am getting an ImportError: cannot import name 'list_of_strings' from idaes.core.util.config

**Comment by andrewlee94** [comment]
@raurr Unfortunately, this is not the correct project for reporting issues with WaterTAP. Please note that `watertap3` is no longer supported and has been replaced by https://github.com/watertap-org/watertap and that any issues should be reported there. Also, when reporting errors like this it will help the developers respond if you can provide a full stack trace to identify what is going on.

From the error message you reported however, I believe the issue is the fact that `watertap3` is no longer maintained and relies on an older version of IDAES.

**Comment by raurr** [comment]
Thank you!
